#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v13
# autospec commit: dc0ff31
#
Name     : qtkeychain
Version  : 0.14.3
Release  : 8
URL      : https://github.com/frankosterfeld/qtkeychain/archive/0.14.3/qtkeychain-0.14.3.tar.gz
Source0  : https://github.com/frankosterfeld/qtkeychain/archive/0.14.3/qtkeychain-0.14.3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: qtkeychain-data = %{version}-%{release}
Requires: qtkeychain-lib = %{version}-%{release}
Requires: qtkeychain-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-qt6
BuildRequires : pkgconfig(libsecret-1)
BuildRequires : qt6base-dev
BuildRequires : qtbase-dev mesa-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
QtKeychain
==========
QtKeychain is a Qt API to store passwords and other secret data securely. How the data is stored depends on the platform:

%package data
Summary: data components for the qtkeychain package.
Group: Data

%description data
data components for the qtkeychain package.


%package dev
Summary: dev components for the qtkeychain package.
Group: Development
Requires: qtkeychain-lib = %{version}-%{release}
Requires: qtkeychain-data = %{version}-%{release}
Provides: qtkeychain-devel = %{version}-%{release}
Requires: qtkeychain = %{version}-%{release}

%description dev
dev components for the qtkeychain package.


%package lib
Summary: lib components for the qtkeychain package.
Group: Libraries
Requires: qtkeychain-data = %{version}-%{release}
Requires: qtkeychain-license = %{version}-%{release}

%description lib
lib components for the qtkeychain package.


%package license
Summary: license components for the qtkeychain package.
Group: Default

%description license
license components for the qtkeychain package.


%prep
%setup -q -n qtkeychain-0.14.3
cd %{_builddir}/qtkeychain-0.14.3
pushd ..
cp -a qtkeychain-0.14.3 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1720037638
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DBUILD_WITH_QT6=ON  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake .. -DBUILD_WITH_QT6=ON  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1720037638
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qtkeychain
cp %{_builddir}/qtkeychain-%{version}/COPYING %{buildroot}/usr/share/package-licenses/qtkeychain/19333c8d229ce8f3a01e1a90ad5c873a6be97459 || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/qt6keychain/translations/qtkeychain_de.qm
/usr/share/qt6keychain/translations/qtkeychain_fr.qm
/usr/share/qt6keychain/translations/qtkeychain_ro.qm
/usr/share/qt6keychain/translations/qtkeychain_ru.qm
/usr/share/qt6keychain/translations/qtkeychain_zh.qm

%files dev
%defattr(-,root,root,-)
/usr/include/qt6keychain/keychain.h
/usr/include/qt6keychain/qkeychain_export.h
/usr/lib64/cmake/Qt6Keychain/Qt6KeychainConfig.cmake
/usr/lib64/cmake/Qt6Keychain/Qt6KeychainConfigVersion.cmake
/usr/lib64/cmake/Qt6Keychain/Qt6KeychainLibraryDepends-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6Keychain/Qt6KeychainLibraryDepends.cmake
/usr/lib64/libqt6keychain.so
/usr/lib64/qt6/mkspecs/modules/qt_Qt6Keychain.pri

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libqt6keychain.so.0.14.3
/usr/lib64/libqt6keychain.so.0.14.3
/usr/lib64/libqt6keychain.so.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qtkeychain/19333c8d229ce8f3a01e1a90ad5c873a6be97459
